src/main/java/fr/xinta/atemia/db/entity/Activity.java
package fr.xinta.atemia.db.entity;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
public class Activity extends AbstractEntity {
    
    private static final int NBCATEGORIES = 3;
    private float production;
    private float terrain;
    private float copil;
    
    private Week week;
    @ManyToOne
    private Person worker;
    @ManyToOne
    private Project project;

    public float getProduction() {
        return production;
    }

    public void setProduction(float production) {
        this.production = production;
    }

    public float getTerrain() {
        return terrain;
    }

    public void setTerrain(float terrain) {
        this.terrain = terrain;
    }

    public float getCopil() {
        return copil;
    }

    public void setCopil(float copil) {
        this.copil = copil;
    }

    public Week getWeek() {
        return week;
    }

    public void setWeek(Week week) {
        this.week = week;
    }

    public Person getWorker() {
        return worker;
    }

    public void setWorker(Person worker) {
        this.worker = worker;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }
    
    public float getNbDaysWork() {
        return production + terrain + copil;
    }

    public int getProductionColspan() {
        if (production == 0) {
            return 0;
        } else {
            int col = NBCATEGORIES;
            if (terrain > 0)
                col--;
            if (copil > 0)
                col--;
            return col;
        }
    }
    
    public int getTerrainColspan() {
        if (terrain == 0) {
            return 0;
        } else {
            int col = NBCATEGORIES - getProductionColspan();
            if (copil > 0)
                col--;
            return col;
        }
    }
    
    public int getCopilColspan() {
        if (copil == 0) {
            return 0;
        } else {
            return NBCATEGORIES - getProductionColspan() - getTerrainColspan();
        }
    }
}

src/main/java/fr/xinta/atemia/db/entity/Person.java
package fr.xinta.atemia.db.entity;

import fr.xinta.atemia.db.facade.Utils;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.TreeMap;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

@Entity
public class Person extends AbstractEntity {
    
    private String firstName;
    private String lastName;
    private int nbDaysAvailable;
    private int production;
    private int prospection;
    private int gestion;
    private int communication;
    private boolean isAdmin;
    
    @ManyToMany(mappedBy="workers")
    private List<Project> projects = new ArrayList<Project>();
    @OneToMany(mappedBy="manager")
    private List<Project> managedProjects = new ArrayList<Project>();
    @OneToMany(mappedBy="worker")
    private List<Activity> activities = new ArrayList<Activity>();
    private TreeMap<String, Float> conges = new TreeMap<String, Float>();

    public String getFirstName() {
	return firstName;
    }

    public void setFirstName(String firstName) {
	this.firstName = firstName;
    }

    public String getLastName() {
	return lastName;
    }

    public void setLastName(String lastName) {
	this.lastName = lastName;
    }

    public int getNbDaysAvailable() {
        return nbDaysAvailable;
    }

    public void setNbDaysAvailable(int nbDaysAvailableByYear) {
        this.nbDaysAvailable = nbDaysAvailableByYear;
    }

    public int getProduction() {
        return production;
    }

    public void setProduction(int production) {
        this.production = production;
    }

    public int getProspection() {
        return prospection;
    }

    public void setProspection(int prospection) {
        this.prospection = prospection;
    }

    public int getGestion() {
        return gestion;
    }

    public void setGestion(int gestion) {
        this.gestion = gestion;
    }

    public int getCommunication() {
        return communication;
    }

    public void setCommunication(int communication) {
        this.communication = communication;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void isAdmin(boolean admin) {
        this.isAdmin = admin;
    }

    public List<Project> getProjects() {
        return projects;
    }
    
    public List<Project> getManagedProjects() {
        return managedProjects;
    }

    public List<Activity> getActivities() {
        return activities;
    }

    public TreeMap<String, Float> getConges() {
        return conges;
    }
    
    public float getNbDaysConges(String week) {
        Float f = getConges().get(week);
        return (f != null) ? f : 0;
    }
    
    public float getNbDaysAffected() {
        float nb = 0;
        for (Activity a : getActivities()) {
            nb += a.getNbDaysWork();
        }
        return nb;
    }
    
    /**
     * @param week the week looked
     * @return the number of days this person work for a given week
     */    
    public Activity getNbDaysAffected(Week week) {
        Activity act = new Activity();
        for (Activity a : getActivities()) {
            if (a.getWeek().compare(week) == 0) {
                act.setProduction(act.getProduction() + a.getProduction());
                act.setTerrain(act.getTerrain() + a.getTerrain());
                act.setCopil(act.getCopil() + a.getCopil());
            }
        }
        return act;
    }
    
    public List<Week> getWeeks() {
        if (getActivities().isEmpty() && getConges().isEmpty())
            return null;
        
        Week startWeek = null;
        Week endWeek = null;
        if (!getActivities().isEmpty()) {
        
            // Get the first and the last week of all project
            startWeek = getActivities().get(0).getWeek();
            endWeek = getActivities().get(0).getWeek();

            for (Activity activity : getActivities()) {
                if (startWeek.compare(activity.getWeek()) < 0) {
                    startWeek = activity.getWeek();
                }
                if (endWeek.compare(activity.getWeek()) > 0) {
                    endWeek = activity.getWeek();
                }
            }
        }
        
        Week firstCongesWeek = null;
        Week lastCongesWeek = null;
        if (!getConges().isEmpty()) {
            try {
                firstCongesWeek = new Week(getConges().firstKey());
                lastCongesWeek = new Week(getConges().lastKey());
            } catch (Exception e) {}
            
            if (getActivities().isEmpty()) {
                startWeek = firstCongesWeek;
                endWeek = lastCongesWeek;
            } else {
                // Check if there is conges before or after that
                if (startWeek.compare(firstCongesWeek) < 0) {
                    startWeek =  firstCongesWeek;
                }
                if (endWeek.compare(lastCongesWeek) > 0) {
                    endWeek =  lastCongesWeek;
                }
            }
        }
        
        return Utils.getWeeks(startWeek, endWeek);
    }
    
    public void removeProject(Project project) {
        removeActivities(project);
        removeProject(project, getProjects().iterator());
    }
    
    public void removeManagedProject(Project project) {
        removeProject(project, getManagedProjects().iterator());
    }
    
    private void removeProject(Project project, Iterator<Project> iterator) {
        boolean notFound = iterator.hasNext();
        while (notFound) {
            Project p = iterator.next();
            if (p.getId() == project.getId()) {
                iterator.remove();
                notFound = false;
            } else {
                notFound = iterator.hasNext();
            }
        }
    }
    
    private void removeActivities(Project project) {
        Iterator<Activity> iterator = getActivities().iterator();
        while (iterator.hasNext()) {
            Activity activity = iterator.next();
            if (activity.getProject().getId() == project.getId()) {
                iterator.remove();
            }
        }
    }
}

src/main/java/fr/xinta/atemia/db/entity/Week.java
package fr.xinta.atemia.db.entity;

import java.io.Serializable;

public class Week implements Serializable{
    
    private int num;
    private int yearOfWeek;

    public Week() {}
    
    public Week(int num, int year) {
        this.num = num;
        this.yearOfWeek = year;
    }
    
    public Week(String s) throws Exception {
        num = Integer.parseInt(s.substring(6, 8));
        yearOfWeek = Integer.parseInt(s.substring(0, 4));
        if (yearOfWeek < 1900 || yearOfWeek > 2500 || num < 1 || num > 52) {
            throw new Exception("Week is not correct (check num < 52)");
        }
    }

    public int getNumber() {
	return num;
    }

    public void setNumber(int num) {
	this.num = num;
    }

    public int getYear() {
        return yearOfWeek;
    }

    public void setYear(int year) {
        this.yearOfWeek = year;
    }
    
    public int compare(Week week) {
        if (week.getYear() == getYear()) {
            return week.getNumber() - getNumber();
        } else {
            return week.getYear() - getYear();
        }
    }

    @Override
    public String toString() {
        return yearOfWeek + "-W" + ((num < 10) ? "0" : "") + num;
    }
}

src/main/webapp/WEB-INF/displayPerson.jsp
<%@ include file="header.jsp" %>
	    
	    <header>
		<form method="post" action="deletePerson">
		    <input type="hidden" name="person-id" value="${person.id}" />
		    <input type="submit" name="delete" value="Delete" />
		</form>
		<form method="post" action="editPerson">
		    <input type="hidden" name="person-id" value="${person.id}" />
		    <input type="submit" name="update" value="Update" />
		</form>
		<form method="post" action="manageConges">
		    <input type="hidden" name="person-id" value="${person.id}" />
		    <input type="submit" name="conges" value="Availability" />
		</form>
		<h1>${person.firstName} ${person.lastName}</h1>
	    </header>
                    
            <c:set var="weeks" value="${person.weeks}" />
	    <c:if test="${not empty weeks}">
                <c:set var="firstWeek" value="${weeks.get(0)}" />
                <div id="person_week" class="accordion">
                    <h3>${firstWeek.year}-W${firstWeek.number}</h3>
                    <div>
                        <table>
                            <tr>
                                <th>Week</th>
                                <th colspan="3">Nb Days Affected</th>
                                <th>Unavailable</th>
                                <th>Total</th>
                            </tr>
                    <c:forEach var="week" items="${weeks}" >
                        <c:if test="${week.number == 1 || week.number == 14 || week.number == 27 || week.number == 40}">
                        </table>
                    </div>
                    <h3>${week.year}-W${week.number}</h3>
                    <div>
                        <table>
                            <tr>
                                <th>Week</th>
                                <th colspan="3">Nb Days Affected</th>
                                <th>Unavailable</th>
                                <th>Total</th>
                            </tr>
                        </c:if>                
                        <c:set var="activity" value="${person.getNbDaysAffected(week)}" />
                        <c:set var="conges" value="${person.getNbDaysConges(week.toString())}" />
                            <tr>
                                <td>${week}</td>
                                <c:choose>
                                    <c:when test="${activity.nbDaysWork == 0}">
                                        <td colspan="3">0.0</td>
                                    </c:when>
                                    <c:otherwise>
                                        <c:if test="${activity.production > 0}">               
                                        <td class="production" colspan="${activity.productionColspan}">
                                            ${activity.production}
                                        </td>
                                        </c:if><c:if test="${activity.terrain > 0}">
                                        <td class="terrain" colspan="${activity.terrainColspan}">
                                            ${activity.terrain}
                                        </td>
                                        </c:if><c:if test="${activity.copil > 0}">
                                        <td class="copil" colspan="${activity.copilColspan}">
                                            ${activity.copil}
                                        </td>
                                        </c:if>
                                    </c:otherwise>
                                </c:choose>
                                <td<c:if test="${conges > 0}"> class="conges"</c:if>>
                                    <a href="manageConges?person-id=${person.id}&amp;week=${week.toString()}">${conges}</a>
                                </td>
                                <td<c:if test="${activity.nbDaysWork + conges > 5}">
                                    style="background-color: red;"
                                </c:if>>${activity.nbDaysWork + conges}</td>
                            </tr>
                        </c:forEach>
                        </table>
                    </div>
                </div>
            </c:if>
            
            <fmt:formatNumber var="ratio" value="${person.nbDaysAffected / person.nbDaysAvailable * 100}" maxFractionDigits="2" />
            <p>${person.firstName} has ${person.nbDaysAffected} affected days on ${person.nbDaysAvailable} days available this year (${ratio}%).<br />
            Days are dispatched between ${person.production}% in production, ${person.prospection}% in prospection,
            ${person.gestion}% in gestion and ${person.communication}% in communication</p>

            <c:choose>
		<c:when test="${empty person.managedProjects}">
		    <p>This person does not manage any project for the moment.</p>
		</c:when>
		<c:otherwise>
                    <p>Managed projects:
                        <c:forEach var="project" items="${person.managedProjects}" >
                            <a href="displayProject?project-id=${project.id}">${project.name}</a>, 
                        </c:forEach>
                    </p>
		</c:otherwise>
	    </c:choose>
            
	    <c:choose>
		<c:when test="${empty person.projects}">
		    <p>This person does not participate to a project for the moment.</p>
		</c:when>
		<c:otherwise>
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Department</th>
                            <th>Nb Days Affected</th>
                            <th>Nb Days Sold</th>
                        </tr>
                        <c:forEach var="project" items="${person.projects}" >
                        <tr>
                            <td><a href="displayProject?project-id=${project.id}">${project.name}</a></td>
                            <td>${project.department}</td>
                            <td>${project.getNbDaysAffected(person.id)}</td>
                            <td>${project.nbDaysSold}</td>
                        </tr>
                        </c:forEach>
                    </table>
		</c:otherwise>
	    </c:choose>
	    
<%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/editActivity.jsp
<%@ include file="header.jsp" %>
	    
	    <header>
		<h1>Editing activity of ${activity.worker.firstName} ${activity.worker.lastName}</h1>
	    </header>
            <p>This worker already has ${activity.worker.getNbDaysConges(activity.week)} days unavailable
                and ${activity.worker.getNbDaysAffected(activity.week).nbDaysWork} days work this week (${activity.week}).</p>                
            <form method="post">
                <input type="hidden" name="activity-id" value="${activity.id}" />
                <table>
                    <tr>
                        <th colspan="2">Please distribute the days of the week between these categories:</th>
                    </tr>
                    <tr class="production">
                        <td>
                            <label for="input_production">Production:</label>
                        </td>
                        <td>
                            <input id="input_production" type="number" name="production"
                                   value="${activity.production}" required autofocus />
                        </td>
                    </tr>
                    <tr class="terrain">
                        <td>
                            <label for="input-terrain">Terrain:</label>
                        </td>			
                        <td>
                            <input id="input-terrain" type="number" name="terrain"
                                   value="${activity.terrain}" required autofocus />
                        </td>
                    </tr>
                    <tr class="copil">
                        <td>
                            <label for="input-copil">Copil:</label>
                        </td>
                        <td>
                            <input id="input-copil" type="number" name="copil"
                                   value="${activity.copil}" required />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="border: 0px;">
                            <input type="submit" name="execute" value="Validate" />
                        </td>
                    </tr>
                </table>
            </form>
	    
<%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/editPerson.jsp
<%@ include file="header.jsp" %>
	    
	    <header>
		<h1>Person</h1>
	    </header>
	    <form method="post">
                <input type="hidden" name="person-id" value="${person.id}" />
		<p><label for="input-first-name">First name :</label></p>
		<p>
		    <input type="text" name="firstName" value="${person.firstName}" id="input-first-name" required autofocus />
		</p>

		<p><label for="input-last-name">Last name :</label></p>
		<p>
		    <input type="text" name="lastName" value="${person.lastName}" id="input-last-name" required />
		</p>

		<p><label for="input-nb-days">Nb days available per year :</label></p>
		<p>
		    <input type="number" name="nbDaysAvailable" value="${person.nbDaysAvailable}" id="input-nb-days" required />
		</p>
                
                <p>These days are dispatched between:</p>
		<p>
                    <label for="input-production">Production:</label>
		    <input type="number" name="production" value="${person.production}" id="input-production"
                           min="0" max="100" required />%
                </p>
                <p>
                    <label for="input-prospection">Prospection:</label>
		    <input type="number" name="prospection" value="${person.prospection}" id="input-prospection"
                           min="0" max="100" required />%
                </p>
                <p>                    
                    <label for="input-gestion">Gestion:</label>
		    <input type="number" name="gestion" value="${person.gestion}" id="input-gestion"
                           min="0" max="100" required />%
                </p>
                <p>   
                    <label for="input-communication">Communication:</label>
		    <input type="number" name="communication" value="${person.communication}" id="input-communication"
                           min="0" max="100" required />%                    
		</p>
                
		<p>
		    <input type="submit" name="execute" value="Validate" />
		</p>
	    </form>
		    
<%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/editProject.jsp
	    <%@ include file="header.jsp" %>

		<header>
		    <h1>Project</h1>
		</header>
		<form method="post">
		    <input type="hidden" name="project-id" value="${project.id}" />
		    <p><label for="input-name">Name:</label></p>
		    <p>
			<input id="input-name" type="text" name="name"
                               value="${project.name}" required autofocus />
		    </p>

		    <p><label for="input-department">Department:</label></p>
		    <p>
                        <select id="input-department" name="department">
                            <option value="DPT" selected>DPT</option>
                            <option value="DEC">DEC</option>
                            <option value="Prospection">Prospection</option>
                            <option value="Gestion">Gestion</option>
                            <option value="Communication">Communication</option>
                            <option value="Développement de produits">Développement de produits</option>
                        </select>
		    </p>
                    
                    <p><label for="input-manager">Manager:</label></p>
                    <p>
                        <input type="text" name="manager-id" id="input-manager"
                               <c:if test="${not empty project.manager}">
                               value="${project.manager.id} ${project.manager.firstName} ${project.manager.lastName}"
                               </c:if>
                               list="list-manager" autocomplete="off" required />
                        <datalist id="list-manager">
                        <c:forEach var="person" items="${persons}" >
                            <option value="${person.id} ${person.firstName} ${person.lastName}">
                        </c:forEach>
                        </datalist>
                    </p>

		    <p><label for="input-nbDaysSold">Number of days sold:</label></p>
		    <p>
			<input id="input-nbDaysSold" type="number" name="nbDaysSold"
                               value="${project.nbDaysSold}" required />
		    </p>
                    
                    <p><label for="input-startWeek">Start week:</label></p>
		    <p>                        
                        <input id="input-startWeek" class="datepicker" type="text" name="startWeek"
                               value="${project.startWeek}" autocomplete="off" required />
                    </p>
                    
                    <p><label for="input-endWeek">End week:</label></p>
		    <p>
			<input id="input-endWeek" class="datepicker" type="text" name="endWeek"
                               value="${project.endWeek}" autocomplete="off" required />
                    </p>

		    <p>
			<input type="submit" name="execute" value="Validate" />
		    </p>
		</form>
			
	    <%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/footer.jsp
	
        </section>
    </body>
</html>

src/main/webapp/WEB-INF/header.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
	<title>Atemia - Projects Manager</title>
	<meta charset="UTF-8" />	
	<meta name="content-type" content="text/html;" charset="utf-8" />
	<link rel="stylesheet" href="./design/style.css" />
	<link rel="stylesheet" href="./design/template.css" />
	<link rel="shortcut icon" type="image/x-icon" href="./design/favicon.ico" />
        
        <!-- jquery for the date picker -->
        <script type="text/javascript" src="./libs/jquery-2.0.0.min.js"></script>
        <script type="text/javascript" src="./libs/jquery-ui-modified.js"></script>
        <script type="text/javascript" src="./ui.js"></script>
        <link rel="stylesheet" href="./libs/jquery-ui.css" />
    </head>
    <body>		
	<section id="panel">
	    <header>
		<a href="http://atemia.org/" target="_blank">
		    <img id="logo" src="./design/logo.png" alt="logo" title="logo" />
		</a>
		<h1><a href="index">Projects Manager</a></h1>
	    </header>

	    <menu id="menu" type="toolbar">
	    <li>
		<h2>Persons</h2>
		<menu class="submenu">
		    <li><a href="createPerson">Create</a></li>
		    <li><a href="listPerson">List</a></li>
		</menu>
	    </li>
	    <li>
		<h2>Projects</h2>
		<menu class="submenu">
		    <li><a href="createProject">Create</a></li>
		    <li><a href="listProject">List</a></li>
		</menu>
	    </li>
	    </menu>

	    <footer>
                <a href="changelog">v2.0</a><br />
		Application developed by <a href="http://www.xinta.fr">Xinta</a><br />
		Source code available <a href="https://github.com/Flaburgan/atemia-projects-manager">on Github</a>
	    </footer>
	</section>

	<section id="content">
	    <c:if test="${not empty error_notification}">
                <p class="error">Error: ${error_notification}</p>
	    </c:if>
                
	    <c:if test="${not empty warning_notification}">
                <p class="warning">Warning: ${warning_notification}</p>
	    </c:if>
                
	    <c:if test="${not empty info_notification}">
                <p class="info">${info_notification}</p>
	    </c:if>
                
            <c:if test="${not empty confirmation_message}">
                <div class="box">
                    <div class="message-confirm">
                        <p>${confirmation_message}</p>
                        <form method="post">
                            <input type="hidden" name="id" value="${id}" />
                            <input type="hidden" name="execute" value="ok" />
                            <input type="submit" name="yes" value="Yes" />
                            <input type="submit" name="no" value="No" />
                        </form>
                    </div>
                </div>
	    </c:if>

src/main/webapp/WEB-INF/index.jsp
<%@ include file="header.jsp" %>
	    
	    <header>
		<h1>Home</h1>
	    </header>

	    <p>Welcome in the Atemia projects manager. This application allows you to easily
	    manage projects and human resources on a planning. We hope you'll enjoy it.</p>
            
            <table>
                <tr>
                    <th colspan="2"><h2>Global indicators</h2></th>
                </tr>
                <tr>
                    <th>Persons</th>
                    <td><a href="listPerson">${nbPersons}</a></td>
                </tr>
                <tr>
                    <th>Projects</th>
                    <td><a href="listProject">${nbProjects}</a></td>
                </tr>
                <tr>
                    <th>Working ratio (days)</th>
                    <fmt:formatNumber var="ratio" value="${daysWorked / daysAvailable * 100}" maxFractionDigits="2" />
                    <td>${daysWorked} / ${daysAvailable} (${ratio}%)</td>
                </tr>
            </table>
<!--                <div id="chart1" style="height:200px;width:400px;"></div>
                <script type="text/javascript">
                $(document).ready(function(){
                    var data = [
                        
                      ['Heavy Industry', 12],['Retail', 9], ['Light Industry', 14],
                      ['Out of home', 16],['Commuting', 7], ['Orientation', 9]
                    ];
                    var plot1 = jQuery.jqplot ('chart1', [data],
                      {
                        seriesDefaults: {
                          // Make this a pie chart.
                          renderer: jQuery.jqplot.PieRenderer,
                          rendererOptions: {
                            // Put data labels on the pie slices.
                            // By default, labels show the percentage of the slice.
                            showDataLabels: true
                          }
                        },
                        legend: { show:true, location: 'e' }
                      }
                    );
                  });
</script>-->
	    
<%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/listPerson.jsp
<%@ include file="header.jsp" %>
	    
	    <header>
		<h1>Persons in the application</h1>
	    </header>


	    <c:choose>
		<c:when test="${empty persons}">
		    <p>There is nobody in the application for the moment. <a href="createPerson">Create one</a>.</p>
		</c:when>
		<c:otherwise>
		    <table>
			<tr>
			    <th>First Name</th>
			    <th>Last Name</th>
			    <th>Ratio</th>
			</tr>
			<c:forEach var="person" items="${persons}" >
                            <fmt:formatNumber var="ratio" value="${person.nbDaysAffected / person.nbDaysAvailable * 100}" maxFractionDigits="2" />
			<tr>
			    <td><a href="displayPerson?person-id=${person.id}">
				    <c:out value="${person.firstName}" />
				</a></td>
			    <td><c:out value="${person.lastName}" /></td>
                            <td>${ratio}%</td>
			</tr>
			</c:forEach>			    
		    </table>
		</c:otherwise>
	    </c:choose>
	    
<%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/listProject.jsp
<%@ include file="header.jsp" %>
	    
	    <header>
		<h1>Projects in the application</h1>
	    </header>

	    <c:choose>
		<c:when test="${empty projects}">
                    <p>There is no projects in the application for the moment. <a href="createProject">Create one</a>.</p>
		</c:when>
		<c:otherwise>
		    <table>
			<tr>
			    <th>Name</th>
			    <th>Department</th>
			    <th>Number of days affected</th>
			    <th>Number of days sold</th>
			</tr>
			<c:forEach var="project" items="${projects}">
			<tr>
			    <td>
				<a href="displayProject?project-id=${project.id}">
				    <c:out value="${project.name}" />
				</a>
			    </td>
			    <td><c:out value="${project.department}" /></td>
			    <td><c:out value="${project.nbDaysAffected}" /></td>
			    <td><c:out value="${project.nbDaysSold}" /></td>
			</tr>
			</c:forEach>			    
		    </table>
		</c:otherwise>
	    </c:choose>
	    
<%@ include file="footer.jsp" %>